[project]
name = "kafka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "quixstreams>=3.16.1",
    "streamlit>=1.45.1",
]
